### ISSUE TITLE
Not able to perform some queries of the benchmark

### ISSUE THREAD

**Issue by erikzenker** [ontop/npd-benchmark#1]
I tested this benchmark with the 'ontop-distribution-1.14.0' tool-chain

and queries 12, 15, 16, 17, 18 , 19 fail by exception like : 

```
...
java.lang.RuntimeException: The builtin function Sum
   Var (name=g)
 is not supported yet!
    at it.unibz.krdb.obda.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.getBuiltinFunctionTerm(SparqlAlgebraToDatalogTranslator.java:1393)
    at it.unibz.krdb.obda.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.getBooleanTerm(SparqlAlgebraToDatalogTranslator.java:1230)
    at it.unibz.krdb.obda.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:261)
    at it.unibz.krdb.obda.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:236)
    at it.unibz.krdb.obda.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:635)
    at it.unibz.krdb.obda.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:208)
    at it.unibz.krdb.obda.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:598)
    at it.unibz.krdb.obda.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:202)
    at it.unibz.krdb.obda.owlrefplatform.core.translator.SparqlAlgebraToDatalogTranslator.translate(SparqlAlgebraToDatalogTranslator.java:152)
    at it.unibz.krdb.obda.owlrefplatform.core.QuestStatement.translateAndPreProcess(QuestStatement.java:428)
    at it.unibz.krdb.obda.owlrefplatform.core.QuestStatement.getUnfolding(QuestStatement.java:666)
    at it.unibz.krdb.obda.owlrefplatform.core.QuestStatement$QueryExecutionThread.run(QuestStatement.java:219)
java.lang.RuntimeException: The builtin function Sum
...
```

So I wonder with which kind of version the benchmark was performed
in the referenced papers ?

**Comment by ghxiao** [comment]
The queries without aggregations were run with the latest stable version 1.14.

The queries with aggregations were run with a version  compiled from the version2 branch, which is not officially released yet. If you are interested, you can compile it by yourself.
